set curpath=%cd%

cd %1

git config user.email %4
git config user.name %5
git add -A || goto :error
git diff-index --quiet HEAD || git commit -a -m "SDK regenerated by CI server" || goto :error
git push %2 %3 || goto :error

goto :EOF

:error
cd %curpath%
echo Failed with git error #%errorlevel%.
exit /b 1