set curpath=%cd%

cd %1

git add -A || goto :error
git commit -a -m "SDK regenerated by CI server" || exit /b 0
git push %2 %3 || goto :error

goto :EOF

:error
cd %curpath%
echo Failed with git error #%errorlevel%.
exit /b 1